### ISSUE TITLE
代码生成器多次点击编辑，字段列表会多次渲染

### ISSUE THREAD

**Issue by AmaliaDhiaz** [kanyxmo/MineAdmin-Vue#1]
![image](https://user-images.githubusercontent.com/107642898/183352787-a657a849-7846-4d7c-b331-e060d4fbf8e3.png)

**Comment by AmaliaDhiaz** [comment]
顺带问一下大佬，新版是没表单生成器了吗

**Comment by kanyxmo** [comment]
嗯，这个bug我也发现了。

新版不需要表单生成器了，有自主开发的ma-form组件，到时候有会相应的文档，json化配置动态生成表单
