### ISSUE TITLE
可以将crud中的beforeAdd和beforeEdit改为同步操作吗 

### ISSUE THREAD

**Issue by 1351681837** [kanyxmo/MineAdmin-Vue#18]
可以将crud中的beforeAdd和beforeEdit改为同步操作吗  因为在提交之前可能会在其中进行一些操作 会消耗一些时间 比如说提交的时候进行上传操作 上传完成后改变form的值  但是现在还在上传就执行了上传函数

**Comment by kanyxmo** [comment]
嗯，这个可以
