### ISSUE TITLE
提交表单错误提示信息的问题

### ISSUE THREAD

**Issue by putyy** [kanyxmo/MineAdmin-Vue#19]
在代码生成器编辑提交请求后端，返回错误信息后 不关闭表单弹窗是不是好一些呢？
其他地方应该也有这样的情况

**Comment by kanyxmo** [comment]
是的，建议挺好的，因为关闭了会导致填写的数据丢失，用户体验不是太好。但目前手头事比较多，优先级不是太高。会找个时间全面检查优化一下这个地方

**Comment by putyy** [comment]
是的 整个框架封装很棒，相信会越来越完善！[强]

**Comment by kanyxmo** [comment]
已完成
