### ISSUE TITLE
使用curd组件中的分组表头时 新增与编辑会报错

### ISSUE THREAD

**Issue by UnrealRoad** [kanyxmo/MineAdmin-Vue#23]
![image](https://user-images.githubusercontent.com/34133693/220813675-d7da9d73-e8a2-4437-b7a4-245f3b1273b8.png)
进行添加操作时会有下面的提示 并且表单是显示的'省市区'一个字段 而不是预期中 省 市 区 三个字段
![image](https://user-images.githubusercontent.com/34133693/220813717-56abcb56-b2b5-42b8-9396-6cd350110ccd.png)

**Comment by kanyxmo** [comment]
children 的定义跟表单没关系，仅仅是分组表头的使用。你的省市区需要定义一个dataIndex，并且设置表单不可见
再设置三个字段与省市区平级，同时表格列不可见就可以了
