### ISSUE TITLE
希望增加字典缓存处理及ma-table开放字典转换接口

### ISSUE THREAD

**Issue by zio-zhang** [kanyxmo/MineAdmin-Vue#32]
1、系统的字典，短时间内一般不会变动，可以缓存处理，减少请求
2、ma-table组件，有时要定制显示字段，如是字典字段，不太好获取字典数据

**Comment by kanyxmo** [comment]
1.字典后台有缓存，前端缓存多此一举了。清除缓存也麻烦
2.新版crud组件有获取字典数据的方法，可以先获取组件内部的formRef，在通过formRef调用getDistlist()。老版本就没办法了

**Comment by zio-zhang** [comment]
> 1.字典后台有缓存，前端缓存多此一举了。清除缓存也麻烦 2.新版crud组件有获取字典数据的方法，可以先获取组件内部的formRef，在通过formRef调用getDistlist()。老版本就没办法了

前端还是有必要的，尤其是表格数据字典字段多时，，请求会占用时间，导致变慢

**Comment by zio-zhang** [comment]
字典的话，可以有一个是否启用缓存的选项，默认不开启，代码自己开启就好了

**Comment by zio-zhang** [comment]
请求过一次就不在请求了，只存内存，清缓存也容易
主要是一个页面，有很多弹窗业务时，这些基本共用的

**Comment by kanyxmo** [comment]
这个会安排上，但优先级不是太高
