### ISSUE TITLE
希望ma-table功能按纽能增加自定义处理函数

### ISSUE THREAD

**Issue by zio-zhang** [kanyxmo/MineAdmin-Vue#33]
在使用ma-table时，有时需要使用自定义的增加修改界面，这时就只能关闭原有的增加修改按纽显示，再在扩展slot中增加按纽，有点麻烦，如能直接在功能配置时写action，不调用默认处理就好
`
const options = reactive({
    // 设置列表API接口
    api: foo.getList,
    // 设置新增接口
    add: {
        show: true,                     // 显示新增按钮
        action: ()=>{addRef.value.open()}                 
        auth: ['foo:save']              // 需要有新增的权限列表
    }
})
`

**Comment by kanyxmo** [comment]
想法很棒，安排
