### ISSUE TITLE
面包屑问题

### ISSUE THREAD

**Issue by kxbyte** [kanyxmo/MineAdmin-Vue#48]
路由地址是多级的时候点击面包屑的仪表盘 路由地址会出错
当前路由
/system/loginlog
点击面包屑仪表盘后应该是
/dashboard
而不是
/system/dashboard

**Comment by kanyxmo** [comment]
没有复现。

**Comment by kxbyte** [comment]
演示地址，问答实例。点面包屑的仪表盘可复现

**Comment by kanyxmo** [comment]
感谢，发现了
