### ISSUE TITLE
本地遇到一个新增操作和编辑操作表单一模一样的问题

### ISSUE THREAD

**Issue by ac8881** [kanyxmo/MineAdmin-Vue#53]
新增的时候表单可以修改，关掉，再点修改，所有只读的表单就变成可以修改的了，反过来一样，比如先点编辑，表单是不可修改的，再点新增，表单本来可以填写的地方，都变成了编辑里面只读的

**Comment by kanyxmo** [comment]
这个bug已经修复，拉取main分支的最新代码即可

**Comment by kanyxmo** [comment]
https://github.com/kanyxmo/MineAdmin-Vue/commit/4515d200bf8557d9564cdee7702d465cff98b567

**Comment by kanyxmo** [comment]
https://github.com/kanyxmo/MineAdmin-Vue/commit/fb08531db6de8b1bce505bff18cc6e0773aba1a7

display问题也可以照此修复下

**Comment by ac8881** [comment]
> 

收到，感谢大佬🙏

**Comment by ac8881** [comment]
> [fb08531](https://github.com/kanyxmo/MineAdmin-Vue/commit/fb08531db6de8b1bce505bff18cc6e0773aba1a7)
> 
> display问题也可以照此修复下

不过使用这个代码还是有一些问题，我最后是这么修改的：

`const formItemDisabled = (item) => {
  let disabledProp = currentAction.value === 'add' ? 'addDisabled' : currentAction.value === 'edit' ? 'editDisabled' : 'disabled';

  if (typeof item[disabledProp] !== 'undefined') {
    return item[disabledProp];
  } else if (typeof item.disabled !== 'undefined') {
    return item.disabled;
  }

  return true;
};
`
