### ISSUE TITLE
提一个建议，分离表格和表单的配置项

### ISSUE THREAD

**Issue by wisp-x** [kanyxmo/MineAdmin-Vue#68]
先感谢开源了这么好用的后台管理框架，易用也好看。不过在使用 crud 组件时，我发现一个尴尬的问题，应该可以使用插槽解决，场景是这样的：
假如表格的搜索表单有个创建时间字段 created_at，我想在搜索的时候使用**时间范围搜索**，配置如下：
```js
  // ...
  {
    title: "创建日期",
    width: 140,
    search: true,
    formType: "range",
    rangeSearch: true,
    dataIndex: "created_at",
    addDisplay: true,
    editDisplay: false,
  },
  // ...
```
这个时候我就发现添加表单的创建时间也变成了时间范围选择(实际需求不需要)，我目前的做法是给crud组件自定义了一个prop，将自定义的表单列传入form组件实现的，不知道有没有更好的解决方法。

有尝试过自己自定义表单组件，但是感觉有点为了这口醋包了顿饺子的感觉。table 表格和表单字段差异比较大，如果分开设置不同的字段配置，form的组件操作空间是不是会更大些？个人拙见。

**Comment by kanyxmo** [comment]
嗯，会考虑这一块如何区分。
目前给你一个解决方案，就是用俩相同的配置，一个设置搜索不可见，一个设置表单不可见
